"""Add sets_p1, sets_p2 in matches table and sets_history table

Revision ID: 022bf8225557
Revises: 6c1155d27563
Create Date: 2026-05-07 21:14:57.464033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022bf8225557'
down_revision: Union[str, Sequence[str], None] = '6c1155d27563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('player1_games', sa.Integer(), nullable=False),
    sa.Column('player2_games', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('matches', sa.Column('sets_p1', sa.Integer(), server_default='0', nullable=False))
    op.add_column('matches', sa.Column('sets_p2', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'sets_p2')
    op.drop_column('matches', 'sets_p1')
    op.drop_table('sets_history')
    # ### end Alembic commands ###
