"""Add tiebreak and server_name to matches

Revision ID: 294444ad4625
Revises: 022bf8225557
Create Date: 2026-05-07 22:22:39.841680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294444ad4625'
down_revision: Union[str, Sequence[str], None] = '022bf8225557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('tiebreak', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('matches', sa.Column('server_name', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'server_name')
    op.drop_column('matches', 'tiebreak')
    # ### end Alembic commands ###
