"""Add server_name to sets_history

Revision ID: 307daa82c4b1
Revises: 294444ad4625
Create Date: 2026-05-08 02:07:48.346486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307daa82c4b1'
down_revision: Union[str, Sequence[str], None] = '294444ad4625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets_history', sa.Column('server_name', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets_history', 'server_name')
    # ### end Alembic commands ###
