"""Add players and matches tables

Revision ID: 6c1155d27563
Revises: 
Create Date: 2026-05-07 17:23:35.349044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1155d27563'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player1_name', sa.String(length=100), nullable=False),
    sa.Column('player2_name', sa.String(length=100), nullable=False),
    sa.Column('games_p1', sa.Integer(), nullable=False),
    sa.Column('games_p2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###
