"""Add player_stats table

Revision ID: fae4f3c80dc3
Revises: 307daa82c4b1
Create Date: 2026-05-08 16:05:30.042478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae4f3c80dc3'
down_revision: Union[str, Sequence[str], None] = '307daa82c4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('games_lost', sa.Integer(), nullable=False),
    sa.Column('sets_won', sa.Integer(), nullable=False),
    sa.Column('sets_lost', sa.Integer(), nullable=False),
    sa.Column('rating_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    # ### end Alembic commands ###
